name: Aduit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rustyflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets